// Компактный словарь ключевых слов (en+ru) для фильтра на вкладке «Эмодзи».
// Юникод-символы сами по себе не ищутся по названию — этот map покрывает частые эмодзи;
// не найденный запрос показывает «ничего не найдено», браузинг по категориям остаётся.
export const EMOJI_KEYWORDS: Readonly<Record<string, string>> = {
  '🚀': 'rocket launch startup ракета запуск старт',
  '🎯': 'target goal aim цель мишень',
  '⭐': 'star favorite звезда избранное',
  '🌟': 'star glow звезда сияние',
  '🔥': 'fire hot flame огонь пламя хит',
  '💡': 'idea bulb light идея лампа',
  '📦': 'package box product коробка посылка продукт',
  '🛠️': 'tools build инструменты стройка',
  '⚙️': 'settings gear config настройки шестерёнка',
  '💻': 'laptop code computer ноутбук код',
  '🖥️': 'desktop computer монитор компьютер',
  '📱': 'phone mobile app телефон приложение',
  '🌐': 'web internet world сайт интернет мир',
  '🤖': 'robot bot ai робот бот',
  '🧠': 'brain mind smart мозг ум',
  '🔬': 'science research lab наука микроскоп',
  '🧪': 'test chemistry lab пробирка тест химия',
  '📈': 'growth chart up рост график вверх',
  '📉': 'chart down падение график вниз',
  '📊': 'chart bars stats график статистика диаграмма',
  '💰': 'money bag cash деньги мешок',
  '🏦': 'bank finance банк финансы',
  '💳': 'card payment карта оплата',
  '🛒': 'cart shop store корзина магазин',
  '🏷️': 'tag price label ярлык цена метка',
  '📝': 'note write memo заметка запись',
  '📚': 'books study library книги учёба',
  '📖': 'book read книга чтение',
  '🎵': 'music note музыка нота',
  '🎧': 'headphones music наушники музыка',
  '🎬': 'movie film clapper кино фильм',
  '🎨': 'art paint design искусство дизайн палитра',
  '📷': 'camera photo камера фото',
  '🎮': 'game controller play игра геймпад',
  '🏠': 'home house дом',
  '🏗️': 'construction build стройка кран',
  '🏢': 'office building офис здание',
  '🏭': 'factory завод фабрика',
  '✈️': 'plane travel fly самолёт путешествие',
  '🚗': 'car auto машина авто',
  '🚚': 'truck delivery грузовик доставка',
  '🌱': 'plant grow eco росток эко рост',
  '🌍': 'earth world globe земля мир',
  '☀️': 'sun day солнце день',
  '🌙': 'moon night луна ночь',
  '⚡': 'lightning energy fast молния энергия быстро',
  '❤️': 'heart love красное сердце любовь',
  '💙': 'blue heart синее сердце',
  '💚': 'green heart зелёное сердце',
  '💜': 'purple heart фиолетовое сердце',
  '🧡': 'orange heart оранжевое сердце',
  '💛': 'yellow heart жёлтое сердце',
  '✅': 'check done ok галочка готово',
  '☑️': 'check box чекбокс галочка',
  '✔️': 'check mark галочка',
  '❌': 'cross no error крест ошибка нет',
  '⭕': 'circle round круг',
  '❗': 'exclamation important восклицание важно',
  '❓': 'question вопрос',
  '💬': 'chat message speech чат сообщение',
  '💭': 'thought bubble мысль',
  '🔔': 'bell notification колокол уведомление',
  '🔒': 'lock secure замок защита',
  '🔑': 'key ключ',
  '🔗': 'link chain ссылка цепь',
  '📌': 'pin push булавка закрепить',
  '📎': 'clip attach скрепка',
  '🗂️': 'folders files папки файлы',
  '📁': 'folder папка',
  '📂': 'folder open открытая папка',
  '🗓️': 'calendar date календарь дата',
  '⏰': 'alarm clock time будильник время',
  '⏳': 'hourglass wait песочные часы ожидание',
  '🎉': 'party celebrate конфетти праздник',
  '🎁': 'gift present подарок',
  '🏆': 'trophy win award кубок победа',
  '🥇': 'gold medal first золото медаль первое',
  '👑': 'crown king корона король',
  '💎': 'diamond gem алмаз бриллиант',
  '👍': 'thumbs up like палец лайк',
  '👏': 'clap applause аплодисменты хлопки',
  '🙌': 'hands raise руки ура',
  '🤝': 'handshake deal рукопожатие сделка',
  '💪': 'muscle strong мышца сила',
  '👀': 'eyes look глаза смотреть',
  '🧩': 'puzzle piece пазл',
  '🔧': 'wrench fix гаечный ключ ремонт',
  '🔨': 'hammer build молоток',
  '📍': 'pin location метка точка место',
  '🗺️': 'map карта',
  '🧭': 'compass компас',
  '🛡️': 'shield protect щит защита',
  '⚔️': 'swords battle мечи битва',
  '🎓': 'graduation study выпускной учёба',
  '🌈': 'rainbow радуга',
  '💧': 'water drop капля вода',
  '🌊': 'wave water волна вода',
  '🍀': 'clover luck клевер удача',
  '🌸': 'flower blossom цветок сакура',
  '🐱': 'cat кот кошка',
  '🐶': 'dog собака пёс',
  '🦊': 'fox лиса',
  '🦄': 'unicorn единорог',
};
