import {
  Rocket, Target, Star, Flame, Lightbulb, Package, Wrench, Settings, Cog, Hammer,
  Laptop, Monitor, Smartphone, Globe, Bot, Brain, Microscope, FlaskConical, TestTube, Cpu,
  TrendingUp, BarChart, BarChart3, PieChart, LineChart, Activity, Coins, Wallet, CreditCard, Banknote,
  ShoppingCart, ShoppingBag, Tag, Tags, Receipt, FileText, File, Files, Folder, FolderOpen,
  BookOpen, Book, Library, GraduationCap, PenTool, Pencil, Feather, Brush, Palette, Camera,
  Image, Film, Video, Music, Headphones, Mic, Radio, Gamepad2, Trophy, Medal,
  Award, Crown, Gem, Diamond, Heart, ThumbsUp, Sparkles, Zap, Bolt, Sun,
  Moon, Cloud, CloudRain, Umbrella, Snowflake, Leaf, Sprout, TreePine, Flower2, Bug,
  Home, Building, Building2, Store, Factory, Warehouse, MapPin, Map, Compass, Navigation,
  Car, Plane, Ship, Truck, Bike, Train, Rocket as RocketAlt, Anchor, Send, Mail,
  MessageSquare, MessageCircle, Bell, Phone, Users, User, UserPlus, Contact, Calendar, Clock,
  CheckCircle, CheckSquare, ListTodo, ListChecks, Flag, Bookmark, Pin, Paperclip, Link, Key,
  Lock, Shield, ShieldCheck, Eye, Search, Filter, Server, Database, HardDrive, Cloud as CloudAlt,
  Code, Code2, Terminal, GitBranch, Github, Puzzle, Layers, Grid3x3, LayoutGrid, Kanban,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type LucideEntry = {
  readonly name: string; // экспортное имя lucide, хранится как `lucide:<name>`
  readonly keywords: string; // en+ru через пробел — для фильтра
  readonly Icon: LucideIcon;
};

// Курируемый набор иконок (статические импорты — tree-shakeable, в отличие от
// динамического `import * as lucide`, который затащил бы в бандл всю библиотеку).
export const LUCIDE_ICONS: readonly LucideEntry[] = [
  { name: 'Rocket', keywords: 'rocket launch ракета запуск', Icon: Rocket },
  { name: 'Target', keywords: 'target goal цель мишень', Icon: Target },
  { name: 'Star', keywords: 'star favorite звезда избранное', Icon: Star },
  { name: 'Flame', keywords: 'flame fire огонь пламя', Icon: Flame },
  { name: 'Lightbulb', keywords: 'idea bulb идея лампа', Icon: Lightbulb },
  { name: 'Package', keywords: 'package box коробка посылка', Icon: Package },
  { name: 'Wrench', keywords: 'wrench tool ключ инструмент', Icon: Wrench },
  { name: 'Settings', keywords: 'settings gear настройки шестерёнка', Icon: Settings },
  { name: 'Cog', keywords: 'cog gear механизм', Icon: Cog },
  { name: 'Hammer', keywords: 'hammer build молоток стройка', Icon: Hammer },
  { name: 'Laptop', keywords: 'laptop computer ноутбук', Icon: Laptop },
  { name: 'Monitor', keywords: 'monitor display монитор экран', Icon: Monitor },
  { name: 'Smartphone', keywords: 'phone mobile телефон смартфон', Icon: Smartphone },
  { name: 'Globe', keywords: 'globe web world глобус мир сайт', Icon: Globe },
  { name: 'Bot', keywords: 'bot robot ai бот робот', Icon: Bot },
  { name: 'Brain', keywords: 'brain mind мозг', Icon: Brain },
  { name: 'Microscope', keywords: 'microscope science микроскоп наука', Icon: Microscope },
  { name: 'FlaskConical', keywords: 'flask lab колба лаборатория', Icon: FlaskConical },
  { name: 'TestTube', keywords: 'test tube пробирка тест', Icon: TestTube },
  { name: 'Cpu', keywords: 'cpu chip процессор чип', Icon: Cpu },
  { name: 'TrendingUp', keywords: 'trending growth рост тренд', Icon: TrendingUp },
  { name: 'BarChart', keywords: 'chart bars график диаграмма', Icon: BarChart },
  { name: 'BarChart3', keywords: 'chart bars график статистика', Icon: BarChart3 },
  { name: 'PieChart', keywords: 'pie chart круговая диаграмма', Icon: PieChart },
  { name: 'LineChart', keywords: 'line chart линейный график', Icon: LineChart },
  { name: 'Activity', keywords: 'activity pulse активность пульс', Icon: Activity },
  { name: 'Coins', keywords: 'coins money монеты деньги', Icon: Coins },
  { name: 'Wallet', keywords: 'wallet money кошелёк', Icon: Wallet },
  { name: 'CreditCard', keywords: 'card payment карта оплата', Icon: CreditCard },
  { name: 'Banknote', keywords: 'money cash купюра деньги', Icon: Banknote },
  { name: 'ShoppingCart', keywords: 'cart shop корзина магазин', Icon: ShoppingCart },
  { name: 'ShoppingBag', keywords: 'bag shop пакет покупки', Icon: ShoppingBag },
  { name: 'Tag', keywords: 'tag label ярлык метка', Icon: Tag },
  { name: 'Tags', keywords: 'tags labels метки', Icon: Tags },
  { name: 'Receipt', keywords: 'receipt bill чек счёт', Icon: Receipt },
  { name: 'FileText', keywords: 'file document файл документ', Icon: FileText },
  { name: 'File', keywords: 'file файл', Icon: File },
  { name: 'Files', keywords: 'files файлы', Icon: Files },
  { name: 'Folder', keywords: 'folder папка', Icon: Folder },
  { name: 'FolderOpen', keywords: 'folder open открытая папка', Icon: FolderOpen },
  { name: 'BookOpen', keywords: 'book read книга чтение', Icon: BookOpen },
  { name: 'Book', keywords: 'book книга', Icon: Book },
  { name: 'Library', keywords: 'library библиотека', Icon: Library },
  { name: 'GraduationCap', keywords: 'graduation study учёба выпускной', Icon: GraduationCap },
  { name: 'PenTool', keywords: 'pen design перо дизайн', Icon: PenTool },
  { name: 'Pencil', keywords: 'pencil edit карандаш правка', Icon: Pencil },
  { name: 'Feather', keywords: 'feather write перо', Icon: Feather },
  { name: 'Brush', keywords: 'brush paint кисть', Icon: Brush },
  { name: 'Palette', keywords: 'palette art палитра', Icon: Palette },
  { name: 'Camera', keywords: 'camera photo камера фото', Icon: Camera },
  { name: 'Image', keywords: 'image picture изображение картинка', Icon: Image },
  { name: 'Film', keywords: 'film movie фильм кино', Icon: Film },
  { name: 'Video', keywords: 'video видео', Icon: Video },
  { name: 'Music', keywords: 'music музыка', Icon: Music },
  { name: 'Headphones', keywords: 'headphones наушники', Icon: Headphones },
  { name: 'Mic', keywords: 'mic microphone микрофон', Icon: Mic },
  { name: 'Radio', keywords: 'radio радио', Icon: Radio },
  { name: 'Gamepad2', keywords: 'game controller игра геймпад', Icon: Gamepad2 },
  { name: 'Trophy', keywords: 'trophy win кубок победа', Icon: Trophy },
  { name: 'Medal', keywords: 'medal award медаль', Icon: Medal },
  { name: 'Award', keywords: 'award prize награда', Icon: Award },
  { name: 'Crown', keywords: 'crown king корона', Icon: Crown },
  { name: 'Gem', keywords: 'gem jewel камень самоцвет', Icon: Gem },
  { name: 'Diamond', keywords: 'diamond алмаз ромб', Icon: Diamond },
  { name: 'Heart', keywords: 'heart love сердце любовь', Icon: Heart },
  { name: 'ThumbsUp', keywords: 'like thumbs лайк палец', Icon: ThumbsUp },
  { name: 'Sparkles', keywords: 'sparkles magic блеск магия', Icon: Sparkles },
  { name: 'Zap', keywords: 'zap energy молния энергия', Icon: Zap },
  { name: 'Bolt', keywords: 'bolt болт', Icon: Bolt },
  { name: 'Sun', keywords: 'sun day солнце день', Icon: Sun },
  { name: 'Moon', keywords: 'moon night луна ночь', Icon: Moon },
  { name: 'Cloud', keywords: 'cloud облако', Icon: Cloud },
  { name: 'CloudRain', keywords: 'rain дождь', Icon: CloudRain },
  { name: 'Umbrella', keywords: 'umbrella зонт', Icon: Umbrella },
  { name: 'Snowflake', keywords: 'snow снежинка зима', Icon: Snowflake },
  { name: 'Leaf', keywords: 'leaf лист эко', Icon: Leaf },
  { name: 'Sprout', keywords: 'sprout grow росток', Icon: Sprout },
  { name: 'TreePine', keywords: 'tree дерево ель', Icon: TreePine },
  { name: 'Flower2', keywords: 'flower цветок', Icon: Flower2 },
  { name: 'Bug', keywords: 'bug issue баг жук', Icon: Bug },
  { name: 'Home', keywords: 'home house дом', Icon: Home },
  { name: 'Building', keywords: 'building здание', Icon: Building },
  { name: 'Building2', keywords: 'office building офис', Icon: Building2 },
  { name: 'Store', keywords: 'store shop магазин', Icon: Store },
  { name: 'Factory', keywords: 'factory завод', Icon: Factory },
  { name: 'Warehouse', keywords: 'warehouse склад', Icon: Warehouse },
  { name: 'MapPin', keywords: 'pin location метка точка', Icon: MapPin },
  { name: 'Map', keywords: 'map карта', Icon: Map },
  { name: 'Compass', keywords: 'compass компас', Icon: Compass },
  { name: 'Navigation', keywords: 'navigation навигация', Icon: Navigation },
  { name: 'Car', keywords: 'car машина авто', Icon: Car },
  { name: 'Plane', keywords: 'plane fly самолёт', Icon: Plane },
  { name: 'Ship', keywords: 'ship корабль', Icon: Ship },
  { name: 'Truck', keywords: 'truck delivery грузовик доставка', Icon: Truck },
  { name: 'Bike', keywords: 'bike велосипед', Icon: Bike },
  { name: 'Train', keywords: 'train поезд', Icon: Train },
  { name: 'RocketAlt', keywords: 'rocket space космос', Icon: RocketAlt },
  { name: 'Anchor', keywords: 'anchor якорь', Icon: Anchor },
  { name: 'Send', keywords: 'send отправить', Icon: Send },
  { name: 'Mail', keywords: 'mail email почта', Icon: Mail },
  { name: 'MessageSquare', keywords: 'message chat сообщение чат', Icon: MessageSquare },
  { name: 'MessageCircle', keywords: 'message чат', Icon: MessageCircle },
  { name: 'Bell', keywords: 'bell notification колокол уведомление', Icon: Bell },
  { name: 'Phone', keywords: 'phone call телефон звонок', Icon: Phone },
  { name: 'Users', keywords: 'users team команда люди', Icon: Users },
  { name: 'User', keywords: 'user person пользователь', Icon: User },
  { name: 'UserPlus', keywords: 'add user добавить', Icon: UserPlus },
  { name: 'Contact', keywords: 'contact контакт', Icon: Contact },
  { name: 'Calendar', keywords: 'calendar календарь', Icon: Calendar },
  { name: 'Clock', keywords: 'clock time часы время', Icon: Clock },
  { name: 'CheckCircle', keywords: 'check done галочка готово', Icon: CheckCircle },
  { name: 'CheckSquare', keywords: 'check task чекбокс', Icon: CheckSquare },
  { name: 'ListTodo', keywords: 'todo list задачи список', Icon: ListTodo },
  { name: 'ListChecks', keywords: 'checklist список', Icon: ListChecks },
  { name: 'Flag', keywords: 'flag флаг', Icon: Flag },
  { name: 'Bookmark', keywords: 'bookmark закладка', Icon: Bookmark },
  { name: 'Pin', keywords: 'pin булавка', Icon: Pin },
  { name: 'Paperclip', keywords: 'attach скрепка', Icon: Paperclip },
  { name: 'Link', keywords: 'link ссылка', Icon: Link },
  { name: 'Key', keywords: 'key ключ', Icon: Key },
  { name: 'Lock', keywords: 'lock замок', Icon: Lock },
  { name: 'Shield', keywords: 'shield щит защита', Icon: Shield },
  { name: 'ShieldCheck', keywords: 'secure защита', Icon: ShieldCheck },
  { name: 'Eye', keywords: 'eye view глаз просмотр', Icon: Eye },
  { name: 'Search', keywords: 'search поиск', Icon: Search },
  { name: 'Filter', keywords: 'filter фильтр', Icon: Filter },
  { name: 'Server', keywords: 'server сервер', Icon: Server },
  { name: 'Database', keywords: 'database db база данных', Icon: Database },
  { name: 'HardDrive', keywords: 'disk диск', Icon: HardDrive },
  { name: 'CloudAlt', keywords: 'cloud облако хранилище', Icon: CloudAlt },
  { name: 'Code', keywords: 'code код', Icon: Code },
  { name: 'Code2', keywords: 'code код разработка', Icon: Code2 },
  { name: 'Terminal', keywords: 'terminal консоль', Icon: Terminal },
  { name: 'GitBranch', keywords: 'git branch ветка', Icon: GitBranch },
  { name: 'Github', keywords: 'github', Icon: Github },
  { name: 'Puzzle', keywords: 'puzzle пазл', Icon: Puzzle },
  { name: 'Layers', keywords: 'layers слои', Icon: Layers },
  { name: 'Grid3x3', keywords: 'grid сетка', Icon: Grid3x3 },
  { name: 'LayoutGrid', keywords: 'layout grid раскладка', Icon: LayoutGrid },
  { name: 'Kanban', keywords: 'kanban board доска канбан', Icon: Kanban },
];

export const LUCIDE_MAP: Readonly<Record<string, LucideIcon>> = Object.fromEntries(
  LUCIDE_ICONS.map((e) => [e.name, e.Icon]),
);

// Палитра цветов для lucide-иконок (Notion-style). key хранится в строке иконки как
// `lucide:<Name>:<key>`; 'default' наследует текущий цвет текста (без style.color).
export type LucideColor = { readonly key: string; readonly label: string; readonly hex: string };
export const LUCIDE_COLORS: readonly LucideColor[] = [
  { key: 'default', label: 'По умолчанию', hex: '' },
  { key: 'gray', label: 'Серый', hex: '#8b8b88' },
  { key: 'brown', label: 'Коричневый', hex: '#a3765a' },
  { key: 'orange', label: 'Оранжевый', hex: '#d9730d' },
  { key: 'yellow', label: 'Жёлтый', hex: '#cb912f' },
  { key: 'green', label: 'Зелёный', hex: '#448361' },
  { key: 'blue', label: 'Синий', hex: '#337ea9' },
  { key: 'purple', label: 'Фиолетовый', hex: '#9065b0' },
  { key: 'pink', label: 'Розовый', hex: '#c14c8a' },
  { key: 'red', label: 'Красный', hex: '#d44c47' },
];
export const LUCIDE_COLOR_MAP: Readonly<Record<string, string>> = Object.fromEntries(
  LUCIDE_COLORS.filter((c) => c.hex).map((c) => [c.key, c.hex]),
);
